name: Concurrency Test
on: workflow_dispatch
concurrency: concurrency-test
jobs:
  concurrency-test:
    runs-on: ubuntu-latest
    steps:
      - name: Some Step
        run: sleep 50
        timeout-minutes: 1