name: Concurrency Test
on: workflow_dispatch
concurrency: 
  group: concurrency-test
  cancel-in-progress: true # Run only the last workflow
jobs:
  concurrency-test:
    runs-on: ubuntu-latest
    steps:
      - name: Some Step
        run: sleep 50
        timeout-minutes: 1