name: fifth-workflow
on: 
  issues:
    types:
      - edited
      - deleted
  pull_request:
    types: 
      - assigned
      - closed
jobs:
  run-fiveth-commamnd:
    runs-on: ubuntu-latest
    steps:
      - name: Event Vars
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF