name: Fourteenth Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        id: cache-steps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: "cache-file"
      - name: Display Cache
        run: echo "${{ toJson(steps.cache-steps.outputs) }}"
      - name: Install node_modules
        run: npm install