name: Internal workflow
on:
  workflow_call:
    inputs:
      title:
        description: "Custom title"
        type: string
        default: "Testing test title"
        required: false
jobs:
  console-log:
    runs-on: ubuntu-latest
    steps:
      - name: Print title
        run: echo ${{ inputs.title }}