name: Seventeenth Workflow
on: 
  workflow_dispatch:
    inputs:
      title:
        description: "Custom title"
        type: string
        default: "Testing test title"
        required: false
jobs:
  call-workflow:
    uses: ./.github/workflows/internal-workflow.yml
    with:
      title: ${{ inputs.title }}
  call-external-workflow:
    uses: frolbel/workflows/.github/workflows/workflow.yml@main
    secrets: 
      PASSWORD: ${{ secrets.PASSWORD }}