name: Third workflow
on: push
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          ls -a
      # - uses: actions/checkout@v4
      - name: Copy repo
        run: |
          git init
          git remote origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git switch main
      - name: List files
        run: |
          ls -a